# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kaoyaners' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kaoyaners
  pod 'Alamofire'
  pod 'SKPhotoBrowser'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'SSZipArchive'
  pod 'MJRefresh'

  target 'KaoyanersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KaoyanersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
